name: Read to artifacts
on: push
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Node init
      run: |
        ls
        node generator/index.js
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: |
          generator/*.json
    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
        name: my-artifact
        path: generator/*.json
