name: Read to artifacts
on: push
jobs:
  job_1:
      run-on: ubuntu
    - name: Checkout repository
      use: action/checkout@v2
    - name: Node init
      run: |
        node /generator/index.js
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist-without-markdown
        path: |
          files/**
    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
        name: my-artifact
