name: Read to artifacts
on: 
  workflow_dispatch:
    inputs:
      ms-test:
        description: 'Input test'     
        required: true
        default: 'be_entity'
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Node init
      run: |
        echo ${{toJson(github)}}
      
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: |
          files/*.json


